Very basic core
Percona-Lab/mnogo_exporter pull request #1
Opened 2020-04-14 15:11 UTC by percona-csalguero

- Sandbox
- Connection tests
- Basic metric collecting and renaming

2020-04-14 19:07 UTC, BupycHuk requested changes

2020-04-14 19:07 UTC, BupycHuk commented on docker/test/init-cluster.sh
> +#!/bin/bash
please include a link to the task to replace it with go code

2020-04-14 19:07 UTC, BupycHuk commented on exporter/diagnostic_data_collector_test.go
> +	dsn := fmt.Sprintf("mongodb://%s:%s@%s:%s/admin", username, password, hostname, port)
let's extract DNS generating to some utils package

2020-04-14 19:07 UTC, BupycHuk commented on exporter/diagnostic_data_collector_test.go
> +	pretty.Println(mm)
this test doesn't look like a good one

2020-04-16 10:31 UTC, BupycHuk commented on docker/test/init-cluster.sh
> +#!/bin/bash
https://jira.percona.com/browse/PMM-5753

2020-04-16 10:37 UTC, AlekSi requested changes
Please replace all instances of "Percona backup"

2020-04-16 10:41 UTC, AlekSi commented
Another thing I think we should add now is CI. Let's try GitHub Actions – we are having a great experience with them on SaaS side. @artemgavrilov can provide an initial configuration and help with them in general.

2020-05-25 09:30 UTC, BupycHuk commented on docker/test/init-cluster.sh
> +#!/bin/bash
not addressed yet

2020-05-25 10:13 UTC, BupycHuk commented
@percona-csalguero Merge conflicts, comment from @AlekSi which is not answered nor addressed.

2020-05-29 09:23 UTC, BupycHuk requested changes

2020-05-29 09:23 UTC, BupycHuk commented on exporter/diagnostic_data_collector.go
> +	// cmd := bson.D{{Key: "replSetGetStatus", Value: "1"}}
please remove this comment

2020-05-29 09:23 UTC, BupycHuk commented on exporter/exporter_test.go
>  	ctx, cancel := context.WithTimeout(context.Background(), time.Second)
looks like this function shouldn't be in this file.

2020-05-29 09:23 UTC, BupycHuk commented on Makefile
> +export TEST_MONGODB_S1_RS?=rs1
any reason to have so much env variables?

2020-05-29 09:23 UTC, BupycHuk commented on exporter/metrics.go
>  	case primitive.Timestamp:
please use case list from https://yourbasic.org/golang/switch-statement/ for the cases which should be ignored.

2020-05-29 09:23 UTC, BupycHuk commented on exporter/metrics_test.go
> +//func TestMakeRawMetricName(t *testing.T) {
Commented code should not be pushed to production

2020-05-29 09:23 UTC, BupycHuk commented on main.go
> +	e, err := exporter.New(exporterOpts)
@percona-csalguero Do we have task for API? looks like we missed it.

2020-05-29 10:14 UTC, percona-csalguero commented on Makefile
> +export TEST_MONGODB_S1_RS?=rs1
For the sandbox, we need 3 servers for RS1, 3 for RS2, 1 config server, 1 mongos server and one stand alone server. via this variables we can set user, pass, rs names and ports for each one.

2020-05-29 13:21 UTC, percona-csalguero commented on main.go
> +	e, err := exporter.New(exporterOpts)
No. We have independent tasks for each collector

2020-06-01 12:28 UTC, BupycHuk requested changes

2020-06-01 12:28 UTC, BupycHuk commented on .github/workflows/go.yml
>          if [ -f Gopkg.toml ]; then
do we need this check?

2020-06-01 12:28 UTC, BupycHuk commented on .travis.yml
> +  - bin/golangci-lint run -c=.golangci-required.yml --out-format=line-number | bin/reviewdog -f=golangci-lint -level=error -reporter=github-pr-check
.golangci-required.yml is not presented in this PR

2020-06-01 12:28 UTC, BupycHuk commented on .travis.yml
> +  - bin/golangci-lint run -c=.golangci.yml --out-format=line-number | bin/reviewdog -f=golangci-lint -level=error -reporter=github-pr-review
To make it work we need REVIEWDOG_GITHUB_API_TOKEN environment variable

2020-06-01 12:28 UTC, BupycHuk commented on .travis.yml
> +language: go
Do we really need github actions and travis ci in the same time?

2020-06-01 12:28 UTC, BupycHuk commented on exporter/exporter_test.go
> +func TestConnect(t *testing.T) {
I think we should ignore this kind of things in linter.

2020-06-01 12:28 UTC, BupycHuk commented on main.go
> +	e, err := exporter.New(exporterOpts)
But, do we have task for API core? Because I don't see any ability to get these metrics by prometheus.

2020-06-01 15:37 UTC, percona-csalguero commented on main.go
> +	e, err := exporter.New(exporterOpts)
In https://github.com/Percona-Lab/mnogo_exporter/pull/3

    Diagnostic data collector
    Replicaset status collector
    Collstats collector
    Server status collector
    Main parameters
    HTTP server that will support having multiple paths to expose metrics

2020-06-02 15:25 UTC, percona-csalguero commented on .travis.yml
> +language: go
deleted

2020-06-02 15:42 UTC, BupycHuk commented on main.go
> +	e, err := exporter.New(exporterOpts)
please include the link to task about API here

2020-06-02 15:43 UTC, BupycHuk commented on .travis.yml
> +language: go
it's weird, but it's not deleted :)

2020-06-02 16:21 UTC, BupycHuk commented on main.go
>  	"github.com/Percona-Lab/mnogo_exporter/exporter"
Please, fix goimports like we do in other repos.

2020-06-02 16:50 UTC, BupycHuk commented
Can we remove all unrelated code?

2020-06-02 16:50 UTC, BupycHuk commented
Tests are failed

2020-06-03 09:28 UTC, closed without merging

2020-06-03 09:28 UTC, percona-csalguero commented
Closing in favor of https://github.com/Percona-Lab/mnogo_exporter/pull/4