PMM-6292 Updates to test the exporter
Percona-Lab/mnogo_exporter pull request #13
Opened 2020-07-15 23:32 UTC by percona-csalguero

- Updated goreleaser config
- Added instructions about how to build into the README
- Added goreleaser installation to the make init command

2020-07-21 08:32 UTC, puneet0191 commented
@cfsalguero  conflicts fix please

2020-07-25 09:37 UTC, AlekSi requested changes
There are conflicts

2020-07-27 10:35 UTC, BupycHuk requested changes
Please fix merge conflicts and re-request review

2020-07-28 07:50 UTC, BupycHuk approved these changes

2020-07-28 09:36 UTC, AlekSi approved these changes

2020-07-28 09:36 UTC, merged