New make build
Percona-Lab/mnogo_exporter pull request #24
Opened 2020-08-19 14:35 UTC by percona-csalguero

2020-08-19 14:41 UTC, EvgeniyPatlan approved these changes

2020-08-19 14:50 UTC, Sevlin approved these changes

2020-08-19 20:42 UTC, BupycHuk commented on Makefile
> +release:                      ## Build the binaries using goreleaser
should we skip publish?

2020-08-20 08:18 UTC, BupycHuk requested changes
Please fix CI.

2020-08-20 08:21 UTC, alexanderblinkov-percona commented on Makefile
> +release:                      ## Build the binaries using goreleaser
yes

2020-08-20 12:02 UTC, BupycHuk approved these changes

2020-08-20 12:03 UTC, merged