PMM-5757 diagnostic data collector
Percona-Lab/mnogo_exporter pull request #3
Opened 2020-05-28 00:35 UTC by percona-csalguero

- Diagnostic data collector
- Replicaset status collector
- Collstats collector
- Server status collector
- Main parameters
- HTTP server that will support having multiple paths to expose metrics

2020-06-12 15:48 UTC, AlekSi commented on exporter/exporter.go
> +func (e *Exporter) Run() {
That really should be in #4

2020-07-02 10:06 UTC, BupycHuk requested changes
Please fix merge conflicts

2020-07-09 10:41 UTC, BupycHuk requested changes
I remember that you said that you will add API as part of this PR, but I don't see it. Will you make separate PR?

2020-07-09 10:41 UTC, BupycHuk commented on exporter/collstats_collector.go
> +		if err := res.Decode(&m); err != nil {
maybe it's better to disable this linter

2020-07-09 10:41 UTC, BupycHuk commented on exporter/replset_status_collector_test.go
> +	client := getTestClient(ctx, t)
Can we add test for ReplsetStatusCollector for cases with no replicaset?

2020-07-09 10:41 UTC, BupycHuk commented on exporter/serverstatus_collector_test.go
> +	c := &diagnosticDataCollector{
`diagnosticDataCollector`?

2020-07-10 09:41 UTC, BupycHuk requested changes
I don't see anything related to `HTTP server that will support having multiple paths to expose metrics`

2020-07-10 09:41 UTC, BupycHuk commented on internal/tu/testutils.go
> +package tu
what does tu means?

2020-07-10 09:41 UTC, BupycHuk commented on internal/tu/testutils.go
> +package tu
please fix golangci linter comments or add ignore comments.

2020-07-10 09:41 UTC, BupycHuk commented on exporter/replset_status_collector_test.go
> +	assert.Error(t, err)
let's use `assert.EqualError`

2020-07-10 12:27 UTC, percona-csalguero commented on internal/tu/testutils.go
> +package tu
test utils

2020-07-10 21:11 UTC, percona-csalguero commented on exporter/replset_status_collector_test.go
> +	assert.Error(t, err)
Improved to detect the Replicaset not yet initialized error

2020-07-14 07:35 UTC, BupycHuk approved these changes

2020-07-14 07:36 UTC, BupycHuk commented
please fix a build.

2020-07-14 11:59 UTC, AlekSi requested changes
CI should pass

2020-07-14 11:59 UTC, AlekSi commented on exporter/collstats_collector.go
> +		if err := res.Decode(&m); err != nil {
Agree

@percona-csalguero ^

2020-07-14 12:52 UTC, percona-csalguero commented
@AlekSi @BupycHuk , CI checks passing

2020-07-14 13:20 UTC, AlekSi requested changes

2020-07-14 13:20 UTC, AlekSi commented on exporter/collstats_collector.go
> +		if err := res.Decode(&m); err != nil {
@percona-csalguero ^^^

2020-07-15 07:34 UTC, BupycHuk approved these changes

2020-07-16 09:03 UTC, AlekSi approved these changes

2020-07-16 17:25 UTC, askomorokhov approved these changes
👍

2020-07-16 20:03 UTC, merged